export enum ActionTypes {
    OPEN_FORM = 'OPEN_FORM',
    CLOSE_FORM = 'CLOSE_FORM',

    FETCH_ALL_SONGS_START = 'FETCH_ALL_SONGS_START',
    FETCH_ALL_SONGS_SUCCESS = 'FETCH_ALL_SONGS_SUCCESS',
    FETCH_ALL_SONGS_FAILED = 'FETCH_ALL_SONGS_FAILED',

    SEARCH_TEXT = 'SEARCH_TEXT',
    SHOW_MUSIC_COMPONENT = 'SHOW_MUSIC_COMPONENT',
    HIDE_MUSIC_COMPONENT = 'HIDE_MUSIC_COMPONENT'
}